# (c) 2016 DataNexus Inc.  All Rights Reserved
---
# Get the AWS credentials associated with the input `ec2_region` from the
# input `credentials_file`
- name: Get {{post_install_task.ec2_region}} credentials from {{post_install_task.credentials_file}}
  include_role:
    name: get-aws-credentials
  vars:
    ec2_region: "{{post_install_task.ec2_region}}"
    credentials_file: "{{post_install_task.credentials_file}}"
  run_once: true
