---
- name: Install/configure confluent servers (kafka and zookeeper)
  hosts: "{{host_inventory}}"
  roles:
    - ensure-interfaces-up
    - setup-web-proxy
    - { role: install-packages, package_list: "{{kafka_package_list}}"}
    - dn-kafka
