---
- name: Create kafka group
  become: true
  group:
    name: kafka
    system: yes
- name: Create kafka user
  become: true
  user:
    name: kafka
    group: kafka
    createhome: no
    system: yes