# (c) 2016 DataNexus Inc.  All Rights Reserved
---
- block:
  - name: Create kafka group
    group:
      name: kafka
      system: yes
  - name: Create kafka user
    user:
      name: kafka
      group: kafka
      createhome: no
      system: yes
  become: true
