# (c) 2016 DataNexus Inc.  All Rights Reserved
- name: Download kafka distribution to /tmp
  become: true
  get_url:
    url: "{{kafka_url}}"
    dest: /tmp
    mode: 0644
    validate_certs: no
  environment: "{{environment_vars}}"
- name: Create "{{kafka_dir}}"
  become: true
  file:
    path: "{{kafka_dir}}"
    state: directory
    owner: kafka
    group: kafka
- name: Unpack kafka distribution into "{{kafka_dir}}"
  become: true
  unarchive:
    copy: no
    src: "/tmp/kafka_2.11-0.10.1.0.tgz"
    dest: "{{kafka_dir}}"
    extra_opts: [ "--strip-components=1" ]
    owner: kafka
    group: kafka
- name: Set values for kafka_bin_dir and kafka_config_dir
  set_fact:
    kafka_bin_dir: "{{kafka_dir}}/bin"
    kafka_config_dir: "{{kafka_dir}}/config"
    kafka_topics_cmd: "{{kafka_dir}}/bin/kafka-topics.sh"
