# (c) 2016 DataNexus Inc.  All Rights Reserved
- include: add-kafka-user.yml static=no tags=install,kafka
- include: install-{{kafka_distro}}-kafka.yml static=no tags=install,kafka
- include: setup-kafka-server-properties.yml static=no tags=install,kafka
- include: create-kafka-services.yml static=no tags=install,kafka
- include: enable-kafka-services.yml static=no tags=service-mgmt,kafka
- include: start-kafka-services.yml static=no tags=service-mgmt,kafka
- name: Pausing before creating requested topics
  command: sleep 10
- include: add-kafka-topics.yml static=no tags=service-mgmt,kafka
