# (c) 2016 DataNexus Inc.  All Rights Reserved
- name: Configure kafka server instance
  become: true
  replace:
    dest: "{{kafka_config_dir}}/server.properties"
    regexp: '^\#(([a-zA-Z]*.?)listeners=PLAINTEXT://).*(:9092)$'
    replace: '\g<1>{{kafka_addr}}\g<3>'
