# (c) 2016 DataNexus Inc.  All Rights Reserved
---
- name: Download kafka distribution to /tmp
  become: true
  get_url:
    url: "{{kafka_url}}"
    dest: /tmp
    mode: 0644
    validate_certs: no
  environment: "{{environment_vars}}"
  tags:
    - always
- name: Create "{{kafka_dir}}"
  become: true
  file:
    path: "{{kafka_dir}}"
    state: directory
    owner: kafka
    group: kafka
  tags:
    - always
- name: Unpack kafka distribution into "{{kafka_dir}}"
  become: true
  unarchive:
    copy: no
    src: "/tmp/kafka_2.11-0.10.1.0.tgz"
    dest: "{{kafka_dir}}"
    extra_opts: [ "--strip-components=1" ]
    owner: kafka
    group: kafka
  tags:
    - always
# Now that we've installed the packages that we need, setup the appropriate `log`
# directories for Zookeeper and/or Kafka (depending on the role, or roles in the
# case of a single-node deployment, that each node will be playing in our cluster)
# and finish by setting up some facts that we'll need later in our playbook
- block:
  - set_fact: log_dir_location="/var/lib"
  - name: Set fact for the log directory location
    set_fact: log_dir_location="{{kafka_log_dir}}"
    when: not (kafka_log_dir is undefined or kafka_log_dir is none or kafka_log_dir | trim == '')
  tags:
    - always
- name: Create apache-zookeeper log directory
  become: true
  file:
    path: "{{log_dir_location}}/zookeeper"
    state: directory
    owner: kafka
    group: kafka
  tags:
    - zookeeper
- name: Create apache-kafka log directory
  become: true
  file:
    path: "{{log_dir_location}}/kafka"
    state: directory
    owner: kafka
    group: kafka
  tags:
    - kafka
- name: Set values for kafka_bin_dir and kafka_config_dir
  set_fact:
    kafka_bin_dir: "{{kafka_dir}}/bin"
    kafka_config_dir: "{{kafka_dir}}/config"
    kafka_topics_cmd: "{{kafka_dir}}/bin/kafka-topics.sh"
  tags:
    - always
