# (c) 2016 DataNexus Inc.  All Rights Reserved
---
- name: Start kafka-zookeeper service
  become: true
  command: systemctl start kafka-zookeeper.service
- name: Pause before starting kafka service
  become: true
  command: sleep 10
- name: Start kafka service
  become: true
  command: systemctl start kafka.service
- name: Pause before starting confluent-schema-registry service
  become: true
  command: sleep 10
  when: kafka_distro == "confluent"
- name: Start confluent-schema-registry service
  become: true
  command: systemctl start confluent-schema-registry.service
  when: kafka_distro == "confluent"
