# (c) 2016 DataNexus Inc.  All Rights Reserved
---
# start up the appropriate services, including the bundled
# kafka-zookeeper service if we are performing a single-node
# kafka deployment
- block:
  - name: Start bundled kafka-zookeeper service
    command: systemctl start kafka-zookeeper.service
    when: (zookeeper_nodes | default([])) == []
  - name: Pause before starting kafka service
    command: sleep 10
  - name: Start kafka service
    command: systemctl start kafka.service
  - name: Pause before starting confluent-schema-registry service
    command: sleep 10
    when: kafka_distro == "confluent"
  - name: Start confluent-schema-registry service
    command: systemctl start confluent-schema-registry.service
    when: kafka_distro == "confluent"
  become: true
